import { WaterSystem, SurveillanceRecord, NormativeParameters, UserGuardianProfile, ChlorineProduct } from '../types';

export const INITIAL_NORMATIVE: NormativeParameters = {
  minFreeChlorine: 0.5,
  optimumMinFreeChlorine: 0.8,
  optimumMaxFreeChlorine: 1.5,
  maxFreeChlorine: 2.0,
  minContactTimeMinutes: 30,
  maxTurbidityNtu: 5.0,
  minPh: 6.5,
  maxPh: 8.5,
  regulationTitle: 'D.S. N.° 031-2010-SA — Reglamento de la Calidad del Agua para Consumo Humano',
  lastUpdated: 'Marzo 2024 (Vigente MINSA/DIGESA)',
};

export const COMMON_PRODUCTS: ChlorineProduct[] = [
  {
    type: 'sodium_hypochlorite',
    name: 'Hipoclorito de Sodio (Líquido comercial)',
    form: 'liquid',
    concentrationPercent: 12.0,
    description: 'Solución líquida concentrada grado potabilización (10% - 13% cloro activo)',
  },
  {
    type: 'sodium_hypochlorite',
    name: 'Hipoclorito de Sodio (Lejía doméstica / Rural)',
    form: 'liquid',
    concentrationPercent: 7.5,
    description: 'Comúnmente distribuido en botellones y sistemas comunitarios JASS (7% - 8%)',
  },
  {
    type: 'sodium_hypochlorite',
    name: 'Hipoclorito de Sodio (Solución diluida)',
    form: 'liquid',
    concentrationPercent: 5.0,
    description: 'Concentración baja apta para desinfección preventiva básica',
  },
  {
    type: 'calcium_hypochlorite',
    name: 'Hipoclorito de Calcio (Granular)',
    form: 'granular',
    concentrationPercent: 68.0,
    description: 'Gránulos secos de alta estabilidad para reservorios rurales (65% - 70%)',
  },
  {
    type: 'trichlor',
    name: 'Pastillas de Tricloro / Cloro Lento',
    form: 'tablets',
    concentrationPercent: 90.0,
    description: 'Tabletas de lenta disolución para dosificadores de erosión (90% pureza)',
  },
];

export const INITIAL_SYSTEMS: WaterSystem[] = [
  {
    id: 'sys-01',
    name: 'Acuífero Alfa - Tanque Central',
    centerPoblado: 'Sector 1 - Red Principal',
    district: 'Lucma',
    province: 'Gran Chimú',
    department: 'La Libertad',
    tankType: 'cylindrical_vertical',
    capacityLiters: 250000,
    currentVolumeLiters: 210000,
    waterSource: 'Manantial de ladera con captación protegida',
    responsible: 'Ing. Carlos Mendoza (JASS)',
    lastChlorinePpm: 1.9,
    ph: 7.4,
    turbidityNtu: 0.4,
    operationalStatus: 'active',
    disinfectionMethod: 'Goteo Constante con Cámara de Carga',
    observations: 'Sistema en óptimas condiciones. Telemetría IoT en línea.',
    updatedAt: 'Hoy • 10:45 AM',
    tier: 'TIER III',
  },
  {
    id: 'sys-02',
    name: 'Cisterna Planta Norte',
    centerPoblado: 'Sector Industrial Norte',
    district: 'Huamachuco',
    province: 'Sánchez Carrión',
    department: 'La Libertad',
    tankType: 'rectangular_cistern',
    capacityLiters: 120000,
    currentVolumeLiters: 96000,
    waterSource: 'Pozo perforado profundo #2',
    responsible: 'Tec. Marina Quispe (Área Técnica Municipal)',
    lastChlorinePpm: 0.6,
    ph: 7.1,
    turbidityNtu: 1.2,
    operationalStatus: 'alert',
    disinfectionMethod: 'Bomba Dosificadora Electromagnética',
    observations: 'Alerta de cloro bajo (0.6 ppm). Requiere dosificación correctiva urgente.',
    updatedAt: 'Hoy • 08:30 AM',
    tier: 'TIER II',
  },
  {
    id: 'sys-03',
    name: 'Cisterna Escolar San Martín',
    centerPoblado: 'Sector 4 - Escuela Primaria',
    district: 'Otuzco',
    province: 'Otuzco',
    department: 'La Libertad',
    tankType: 'rectangular_cistern',
    capacityLiters: 250000,
    currentVolumeLiters: 155000,
    waterSource: 'Red municipal con cisterna compensadora',
    responsible: 'Prof. Luis Alva (Comité de Salud Escolar)',
    lastChlorinePpm: 1.4,
    ph: 7.2,
    turbidityNtu: 0.8,
    operationalStatus: 'maintenance',
    disinfectionMethod: 'Dosificador por Erosión de Pastillas',
    observations: 'Mantenimiento de filtros programado para hoy.',
    updatedAt: 'Ayer • 04:20 PM',
    tier: 'TIER I',
  },
  {
    id: 'sys-04',
    name: 'Pozo Artesiano No. 4',
    centerPoblado: 'Comunidad Los Laureles',
    district: 'Simbal',
    province: 'Trujillo',
    department: 'La Libertad',
    tankType: 'cylindrical_vertical',
    capacityLiters: 180000,
    currentVolumeLiters: 163800,
    waterSource: 'Acuífero subterráneo aluvial',
    responsible: 'Rosa Benites (Promotora de Salud)',
    lastChlorinePpm: 1.7,
    ph: 7.3,
    turbidityNtu: 0.5,
    operationalStatus: 'active',
    disinfectionMethod: 'Clorador por Goteo Adaptado',
    observations: 'Nivel freático estable, parámetros microbiológicos en regla.',
    updatedAt: 'Hace 2 días',
    tier: 'TIER II',
  },
  {
    id: 'sys-05',
    name: 'Tanque Elevado 50,000L',
    centerPoblado: 'Barrio Alto Progreso',
    district: 'Moche',
    province: 'Trujillo',
    department: 'La Libertad',
    tankType: 'cylindrical_vertical',
    capacityLiters: 50000,
    currentVolumeLiters: 42000,
    waterSource: 'Estación de Bombeo Intermedia',
    responsible: 'Juan Pérez (Operador Municipal)',
    lastChlorinePpm: 1.8,
    ph: 7.2,
    turbidityNtu: 0.6,
    operationalStatus: 'active',
    disinfectionMethod: 'Goteo con Solución Madre',
    observations: 'Dosificado hace 2 horas, cloro libre estabilizado en 1.8 ppm.',
    updatedAt: 'Hoy • 06:15 AM',
    tier: 'TIER II',
  },
];

export const INITIAL_RECORDS: SurveillanceRecord[] = [
  {
    id: 'rec-01',
    timestamp: new Date().toISOString(),
    dateStr: 'Hoy',
    timeStr: '10:45 AM',
    systemId: 'sys-02',
    systemName: 'Dosificación Exitosa - Cisterna Norte',
    centerPoblado: 'Sector Industrial Norte',
    measurementPoint: 'Salida de Reservorio',
    volumeLiters: 120000,
    productName: 'Hipoclorito de Sodio Líquido',
    concentrationPercent: 12.0,
    initialChlorinePpm: 0.6,
    targetChlorinePpm: 2.0,
    calculatedDoseValue: 1400,
    calculatedDoseUnit: 'mL',
    postChlorinePpm: 2.0,
    contactTimeMinutes: 30,
    status: 'optimal',
    ph: 7.2,
    turbidityNtu: 0.4,
    temperatureC: 21.4,
    responsible: 'Tec. Marina Quispe',
    observations: '+1,400 ml Hipoclorito de Sodio (12%) • Cloro final estabilizado en 2.0 ppm certificado.',
    xpEarned: 50,
    isAudited: true,
  },
  {
    id: 'rec-02',
    timestamp: new Date(Date.now() - 86400000).toISOString(),
    dateStr: 'Ayer',
    timeStr: '04:20 PM',
    systemId: 'sys-01',
    systemName: 'Lectura de Rutina - Acuífero Alfa',
    centerPoblado: 'Sector 1 - Red Principal',
    measurementPoint: 'Primer Grifo de la Red',
    volumeLiters: 250000,
    productName: 'Hipoclorito de Calcio',
    concentrationPercent: 68.0,
    initialChlorinePpm: 1.9,
    targetChlorinePpm: 1.9,
    calculatedDoseValue: 0,
    calculatedDoseUnit: 'g',
    postChlorinePpm: 1.9,
    contactTimeMinutes: 45,
    status: 'optimal',
    ph: 7.2,
    turbidityNtu: 0.4,
    temperatureC: 22.1,
    responsible: 'Ing. Carlos Mendoza',
    observations: '1.9 ppm Cl₂ Libre • pH 7.2 • Turbidez 0.4 NTU (Óptimo y Cristalino). Sensor multiparámetro #04.',
    xpEarned: 20,
    isAudited: true,
  },
  {
    id: 'rec-03',
    timestamp: new Date(Date.now() - 172800000).toISOString(),
    dateStr: 'Hace 2 días',
    timeStr: '08:15 AM',
    systemId: 'sys-05',
    systemName: 'Recuperación de Cloro - Tanque Elevado',
    centerPoblado: 'Barrio Alto Progreso',
    measurementPoint: 'Tanque Cabecera',
    volumeLiters: 50000,
    productName: 'Hipoclorito de Calcio (68%)',
    concentrationPercent: 68.0,
    initialChlorinePpm: 0.5,
    targetChlorinePpm: 1.8,
    calculatedDoseValue: 600,
    calculatedDoseUnit: 'g',
    postChlorinePpm: 1.8,
    contactTimeMinutes: 35,
    status: 'optimal',
    ph: 7.3,
    turbidityNtu: 0.6,
    temperatureC: 20.8,
    responsible: 'Juan Pérez',
    observations: 'Corrección preventiva: Subió de 0.5 ppm a 1.8 ppm con +600g Hipoclorito de Calcio. Misión crítica neutralizada.',
    xpEarned: 75,
    isAudited: true,
  },
];

export const INITIAL_GUARDIAN: UserGuardianProfile = {
  level: 4,
  title: 'Guardián Potable',
  currentXp: 2450,
  nextLevelXp: 3000,
  streakDays: 14,
  totalVolumeTreatedLiters: 800000,
  achievementsUnlocked: 8,
  totalAchievements: 12,
};
